Pundit policies
wolox-training/mec-rails pull request #14
Opened 2018-12-11 16:25 UTC by mcolombo87

### Summary
New Policy for Users' Rent. An authenticated user only can see his rents, if he try to get any other an 403 code will be shoot it.
### ScreenShots
![image](https://user-images.githubusercontent.com/8608635/49814205-e9187680-fd47-11e8-8be8-47bcb7fb652b.png)
### Trello
https://trello.com/c/sin69Z80/12-instalar-y-configurar-pundit

2018-12-11 18:25 UTC, facucompe requested changes

2018-12-11 18:25 UTC, facucompe commented on app/controllers/application_controller.rb
> +    render json: { error: error_message }, status: :forbidden
There is an `:unauthorized` status

2018-12-11 18:25 UTC, facucompe commented on app/controllers/api/v1/rents_controller.rb
> +        authorize user.rents[0]
You are just authorizing the first one

2018-12-11 20:16 UTC, mcolombo87 commented on app/controllers/application_controller.rb
> +    render json: { error: error_message }, status: :forbidden
Yes, but maybe that be confused if the user is authenticated but have restricted access to this information. Forbidden it's best choose for me. 

> 403 Code: "The server understood the request but refuses to authorize it" (https://httpstatuses.com/403)

2018-12-11 20:19 UTC, mcolombo87 commented on app/controllers/api/v1/rents_controller.rb
> +        authorize user.rents[0]
Yes, always will be rents for this user_id, so i not need to check all. Check one is enough.

2018-12-11 20:36 UTC, facucompe commented on app/controllers/api/v1/rents_controller.rb
> +        authorize user.rents[0]
hahah, don't check at all then, usually we only check creation

2018-12-11 20:45 UTC, floresv reviewed
Review it please, Maybe a show of rents ? :thinking:

2018-12-11 20:45 UTC, floresv commented on app/controllers/api/v1/rents_controller.rb
> +        authorize user.rents[0]
mmm.. I think you should see only your rents. Apply a select or filter ?

2018-12-11 21:36 UTC, mcolombo87 commented
@floresv "mmm.. I think you should see only your rents. Apply a select or filter ?" User only see his rents, always. Pundit take care of that.

2018-12-13 18:55 UTC, mcolombo87 commented on app/controllers/api/v1/rents_controller.rb
> +        authorize user.rents[0]
Done!

2018-12-13 20:17 UTC, facucompe approved these changes

2018-12-13 20:40 UTC, merged