Book Suggestion Routes tests
wolox-training/mec-rails pull request #17
Opened 2018-12-12 16:20 UTC by mcolombo87

### Summary
New Tests for Book Suggestions' Routes.
### ScreenShoots
![image](https://user-images.githubusercontent.com/8608635/49882981-84751e80-fe10-11e8-82a1-dfb59950da96.png)
### Trello
https://trello.com/c/swvfOsLw/28-crear-test-para-endpoint-de-creaci%C3%B3n-de-un-booksuggestion

2018-12-13 17:08 UTC, facucompe requested changes

2018-12-13 17:08 UTC, facucompe commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        booksugg_autogenerate = build(:book_suggestion)
Use `attributes_for(:book_suggestion)` instead

2018-12-13 17:08 UTC, facucompe commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        booksugg_autogenerate = build(:book_suggestion)
Same here

2018-12-13 20:03 UTC, mcolombo87 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        booksugg_autogenerate = build(:book_suggestion)
Done!

2018-12-14 16:48 UTC, floresv approved these changes
LGTM

2018-12-17 13:45 UTC, facucompe approved these changes
Change that if you want

2018-12-17 13:45 UTC, facucompe commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        booksugg_autogenerate.as_json(only: %i[price genre])
`booksugg_autogenerate.delete!(:key)`

2018-12-17 15:19 UTC, mcolombo87 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        booksugg_autogenerate.as_json(only: %i[price genre])
That ways is better than my way, I give you that, but I prefer don't modify this PR and move on!

2018-12-17 15:20 UTC, merged