Active Admin
wolox-training/mec-rails pull request #20
Opened 2018-12-14 15:21 UTC by mcolombo87

### Summary
Add Active Admin to this project for manager models.
### ScreenShot
![image](https://user-images.githubusercontent.com/8608635/50011376-b0bca680-ff9a-11e8-886f-712dc44b9057.png)
### Trello
https://trello.com/c/cs5jQUaI/10-instalar-y-configurar-active-admin

2018-12-17 14:08 UTC, facucompe requested changes
Just that small change and we are done

2018-12-17 14:08 UTC, facucompe commented on app/controllers/application_controller.rb
>    include Wor::Paginate
Move `Wor::Paginate` to `ApiController` too

2018-12-18 13:24 UTC, facucompe approved these changes

2018-12-18 15:09 UTC, floresv approved these changes

2018-12-18 15:23 UTC, merged