Devise gem for User Authentication.
wolox-training/mec-rails pull request #4
Opened 2018-11-27 17:05 UTC by mcolombo87

### Summary
Integration with device gem for handler user authentications.
### ScreenShots
![image](https://user-images.githubusercontent.com/8608635/49098203-26134200-f24d-11e8-8f73-84e0518d299f.png)
![image](https://user-images.githubusercontent.com/8608635/49098248-3c210280-f24d-11e8-87db-75f63b411281.png)
### Trello
https://trello.com/c/hpV1zoZf/9-instalar-configurar-devise-y-crear-user

2018-11-27 18:54 UTC, floresv commented
Looks good, resolve conflicts.

2018-11-28 18:48 UTC, facucompe requested changes

2018-11-28 18:48 UTC, facucompe commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
Add `presence` and `uniqueness` validations here

2018-11-28 20:25 UTC, mcolombo87 commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
Done!

2018-12-04 15:01 UTC, facucompe approved these changes

2018-12-04 15:06 UTC, floresv approved these changes

2018-12-04 19:06 UTC, merged